export const INITIALIZE = 'INITIALIZE';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_FRIENDS = 'FETCH_FRIENDS';
export const FETCH_RECENT_MESSAGES = 'FETCH_RECENT_MESSAGES';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const CHECK_USER = 'CHECK_USER';
export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
