export const INITIALIZED = 'INITIALIZED';
export const FRIENDS = 'FRIENDS';
export const FRIENDS_RECENT = 'FRIENDS_RECENT';
export const MESSAGES = 'MESSAGES';
export const TOKEN = 'TOKEN';
export const SELF = 'SELF';
export const MESSAGE = 'MESSAGE';
export const NOTICE_MESSAGE = 'NOTICE_MESSAGE';
export const NOTICE_SHOWING = 'NOTICE_SHOWING';
export const NOTICE_TYPE = 'NOTICE_TYPE';
export const OPERATION_BOX_SHOWING = 'OPERATION_BOX_SHOWING';
export const OPERATION_BOX_PAYLOAD = 'OPERATION_BOX_PAYLOAD';

